--A--
CREATE TABLE MONHOC (
    MAMH VARCHAR(10) PRIMARY KEY,
    TENMH NVARCHAR(50) NOT NULL,
    SOHT INT NOT NULL,
    LOAI NVARCHAR(50) NOT NULL
)

CREATE TABLE SINHVIEN (
    MASV VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(50) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH NVARCHAR(10) NOT NULL,
    QUEQUAN NVARCHAR(50) NOT NULL,
    NOICUTRU NVARCHAR(50) NOT NULL
)

CREATE TABLE DANGKY (
    MSSV VARCHAR(10) NOT NULL,
    MAMH VARCHAR(10) NOT NULL,
    KYHOC INT NOT NULL,
    DIEMQT FLOAT NOT NULL,
    DIEMCK FLOAT NOT NULL,
    PRIMARY KEY (MSSV, MAMH),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

CREATE TABLE MH_GV (
    MAMH VARCHAR(10) NOT NULL,
    TENGV NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MAMH, TENGV),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

INSERT INTO MONHOC VALUES 
('IT1110', N'Tin học đại cương', 4, N'Cơ bản')

INSERT INTO SINHVIEN VALUES
('20131345',N'Nguyễn Văn Hạnh','1995-06-01',N'Nam', N'Lạng Sơn', N'B13 KTX Bách Khoa')

INSERT INTO DANGKY VALUES
('20131345', 'IT1110', 1, 8.5, 7.5)

INSERT INTO MH_GV VALUES
('IT1110', N'Nguyễn Duy Hiệp')

--B--
--1--
SELECT MASV, HOTEN, NGAYSINH, GIOITINH, QUEQUAN
FROM SINHVIEN 
WHERE YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN 18 AND 20

--2--
SELECT mh.MAMH, mh.TENMH
FROM MH_GV mhgv, MONHOC mh
WHERE mhgv.MAMH = mh.MAMH 
GROUP BY mh.MAMH, mh.TENMH
HAVING COUNT(mhgv.TENGV) >=2 

--3--
SELECT sv.MASV, sv.HOTEN, sv.NGAYSINH
FROM SINHVIEN sv, DANGKY dk
WHERE sv.MASV = dk.MSSV
AND dk.KYHOC = 1
GROUP BY sv.MASV, sv.HOTEN, sv.NGAYSINH
HAVING COUNT(dk.MAMH) = (
    SELECT COUNT(dk.MAMH)
    FROM DANGKY dk
    WHERE dk.KYHOC = 1 
)

--4--
SELECT sv.MASV, sv.HOTEN, 
SUM(dk1.DIEMQT*0.4 + dk1.DIEMCK*0.6) AS [Điểm học kì 1],
SUM(dk2.DIEMQT*0.4 + dk2.DIEMCK*0.6) AS [Điểm học kì 2]
FROM SINHVIEN sv, DANGKY dk1, MONHOC mh, DANGKY dk2
WHERE sv.MASV = dk1.MSSV AND dk1.MAMH = mh.MAMH AND dk2.MAMH = mh.MAMH AND sv.MASV = dk2.MSSV
AND mh.MAMH = 'IT1110'
AND dk1.KYHOC = 1 AND dk2.KYHOC = 2
GROUP BY sv.MASV, sv.HOTEN

SELECT sv.MASV, sv.HOTEN,
       SUM(dk1.DIEMQT * 0.4 + dk1.DIEMCK * 0.6) AS [Điểm học kỳ 1],
       SUM(dk2.DIEMQT * 0.4 + dk2.DIEMCK * 0.6) AS [Điểm học kỳ 2]
FROM SINHVIEN sv
JOIN DANGKY dk1 ON sv.MASV = dk1.MSSV
JOIN MONHOC mh ON dk1.MAMH = mh.MAMH
JOIN DANGKY dk2 ON sv.MASV = dk2.MSSV AND dk2.MAMH = mh.MAMH
WHERE mh.MAMH = 'CH3220' AND dk1.KYHOC = 1 AND dk2.KYHOC = 2
GROUP BY sv.MASV, sv.HOTEN;

--5--
SELECT sv.MASV, sv.HOTEN, sv.NGAYSINH
FROM SINHVIEN sv, DANGKY dk, MONHOC mh
WHERE sv.MASV = dk.MSSV AND dk.MAMH = mh.MAMH
AND dk.KYHOC = 1
GROUP BY sv.MASV, sv.HOTEN, sv.NGAYSINH
HAVING SUM(dk.DIEMQT + dk.DIEMCK)*0.5 >= ALL(
    SELECT SUM(dk.DIEMQT + dk.DIEMCK)*0.5
    FROM SINHVIEN sv, DANGKY dk, MONHOC mh
    WHERE sv.MASV = dk.MSSV AND dk.MAMH = mh.MAMH
    AND dk.KYHOC = 1
    GROUP BY sv.MASV
)

--6--
SELECT mh.MAMH, mh.TENMH
FROM MONHOC mh
WHERE mh.LOAI = N'Chuyên ngành'
AND mh.MAMH NOT IN (
    SELECT mh.MAMH
    FROM MONHOC mh, DANGKY dk
    WHERE mh.MAMH = dk.MAMH
    AND dk.KYHOC = 1 
    AND mh.MAMH IN (
        SELECT mh.MAMH
        FROM MONHOC mh, DANGKY dk
        WHERE mh.MAMH = dk.MAMH
        AND dk.KYHOC = 2
    )
)

--7--
SELECT mh.MAMH, mh.TENMH, COUNT(dk.MSSV) AS [Số sinh viên học], COUNT(mhgv.TENGV) AS [Số giáo viên dạy]
FROM DANGKY dk, MONHOC mh, MH_GV mhgv
WHERE dk.MAMH = mh.MAMH AND mh.MAMH = mhgv.MAMH
GROUP BY mh.MAMH, mh.TENMH
HAVING COUNT(dk.MSSV) >= ALL(
    SELECT COUNT(dk.MSSV)
    FROM DANGKY dk, MONHOC mh, MH_GV mhgv
    WHERE dk.MAMH = mh.MAMH AND mh.MAMH = mhgv.MAMH
    GROUP BY mh.MAMH
)
